import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {createHandoff,finalizeSemanticHandoff,exportHandoff,inspectPortable,importHandoff,loadHandoff,validateWorkspace,CONTINUE_PROMPT,listHandoffs} from '../src/handoff.js';
import {createZip,readZip} from '../src/zip.js';
import {createHash} from 'node:crypto';
function temp(p='agy-ho-'){return fs.mkdtempSync(path.join(os.tmpdir(),p));}function git(cwd,args){const r=spawnSync('git',args,{cwd,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();}
function repos(){const base=temp(),bare=path.join(base,'origin.git'),a=path.join(base,'a'),b=path.join(base,'b');git(base,['init','--bare',bare]);git(base,['clone',bare,a]);git(a,['config','user.email','a@example.test']);git(a,['config','user.name','A']);fs.writeFileSync(path.join(a,'README.md'),'hello\n');git(a,['add','README.md']);git(a,['commit','-m','init']);git(a,['push','origin','HEAD:main']);git(base,['clone','--branch','main',bare,b]);return {base,a,b};}
test('portable handoff rebinds to same repo at a different machine path without conversation dependency',()=>{const {a,b}=repos(),conv='12345678-abcd-ef01-2345-6789abcdef01';fs.writeFileSync(path.join(a,'work.txt'),'dirty\n');const h=createHandoff({cwd:a,conversationId:conv,reason:'manual'});assert.ok(fs.existsSync(path.join(h.dir,'HANDOFF.md')));const md=fs.readFileSync(path.join(h.dir,'HANDOFF.md'),'utf8');assert.doesNotMatch(md,new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));const portable=exportHandoff({cwd:a,id:h.handoffId,output:path.join(a,'task.agyh')}),p=inspectPortable(portable);assert.equal(p.manifest.format,'agy-retry-handoff');const imported=importHandoff({cwd:b,file:portable});assert.equal(imported.workspaceValidation.ok,true);const loaded=loadHandoff({cwd:b,id:imported.id});assert.match(loaded.continuePrompt,/Treat the handoff as a checkpoint/);assert.match(CONTINUE_PROMPT,/Machine-specific paths/);assert.equal(validateWorkspace(loaded.workspace,b).ok,true);assert.ok(listHandoffs({cwd:b}).length>=1);});
test('semantic handoff rejects likely secrets and portable corruption is detected',()=>{const {a}=repos(),h=createHandoff({cwd:a,reason:'manual'});assert.throws(()=>finalizeSemanticHandoff({cwd:a,id:h.handoffId,text:'Goal\nTOKEN=supersecret'}),/secret/);finalizeSemanticHandoff({cwd:a,id:h.handoffId,text:'# Goal\n\nContinue safely from verified state.\n'});const file=exportHandoff({cwd:a,id:h.handoffId,output:path.join(a,'ok.agyh')}),buf=fs.readFileSync(file);buf[Math.floor(buf.length/3)]^=1;const bad=path.join(a,'bad.agyh');fs.writeFileSync(bad,buf);assert.throws(()=>inspectPortable(bad),/(CRC|checksum|invalid)/i);});
test('portable mode embeds only explicitly selected safe untracked files and blocks sensitive selections',()=>{const {a,b}=repos();fs.writeFileSync(path.join(a,'notes.txt'),'portable work in progress\n');fs.writeFileSync(path.join(a,'.env'),'TOKEN=do-not-pack\n');const h=createHandoff({cwd:a,reason:'manual',includeUntracked:['notes.txt']});assert.deepEqual(h.includedUntracked,['notes.txt']);assert.equal(fs.readFileSync(path.join(h.dir,'git','untracked-files','notes.txt'),'utf8'),'portable work in progress\n');const file=exportHandoff({cwd:a,id:h.handoffId,output:path.join(a,'wip.agyh')}),p=inspectPortable(file);assert.ok(p.entries.some(x=>x.name==='handoff/git/untracked-files/notes.txt'));const imported=importHandoff({cwd:b,file});assert.equal(fs.readFileSync(path.join(imported.dir,'git','untracked-files','notes.txt'),'utf8'),'portable work in progress\n');assert.throws(()=>createHandoff({cwd:a,reason:'manual',includeUntracked:['.env']}),/sensitive untracked path/);});

test('portable manifest schema fields and checksum manifest are validated before import',()=>{const {a}=repos(),h=createHandoff({cwd:a,reason:'manual'}),file=exportHandoff({cwd:a,id:h.handoffId,output:path.join(a,'schema.agyh')}),entries=readZip(fs.readFileSync(file));const map=new Map(entries.map(e=>[e.name,Buffer.from(e.data)]));const manifest=JSON.parse(map.get('handoff/manifest.json').toString('utf8'));delete manifest.project;map.set('handoff/manifest.json',Buffer.from(JSON.stringify(manifest,null,2)+'\n'));const files={};for(const [name,data] of map)if(name!=='handoff/checksums.json')files[name]=createHash('sha256').update(data).digest('hex');map.set('handoff/checksums.json',Buffer.from(JSON.stringify({algorithm:'sha256',files},null,2)+'\n'));const bad=path.join(a,'bad-schema.agyh');fs.writeFileSync(bad,createZip([...map].map(([name,data])=>({name,data}))));assert.throws(()=>inspectPortable(bad),/invalid handoff manifest field: project/);});
