import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {mergeStatusline,scheduleFromStop,loadNative,scheduleAutoHandoff,runHandoffWorker,renderNativeStatusline,snapshotFromStatusline,metricColorCode} from '../src/native.js';import {DEFAULT_CONTROL_CONFIG,saveControlConfig,setConversationOverride} from '../src/control.js';
function temp(p='agy-v04-'){return fs.mkdtempSync(path.join(os.tmpdir(),p));}const conv='12345678-abcd-ef01-2345-6789abcdef01';
function payload(cwd,extra={}){return {conversation_id:conv,cwd,workspace:{current_dir:cwd},model:{id:'gemini-3.7-flash',display_name:'Gemini 3.7 Flash (Medium)'},context_window:{used_percentage:42,context_window_size:1_000_000},quota:{'gemini-5h':{remaining_fraction:.2,reset_in_seconds:3600},'gemini-weekly':{remaining_fraction:.5,reset_in_seconds:100000}},agent_state:'idle',task_count:0,pending_input_count:0,tool_confirmation_pending:false,terminal_width:120,...extra};}
function withConfig(dir,mutate=()=>{}){const file=path.join(dir,'config.json'),c=JSON.parse(JSON.stringify(DEFAULT_CONTROL_CONFIG));mutate(c);saveControlConfig(c,{file});return file;}
test('weekly quota below threshold hard-blocks retry with zero worker dispatch',()=>{const root=temp(),cwd=temp('agy-work-'),file=withConfig(root),old=process.env.AGY_RETRY_HUD_CONFIG;process.env.AGY_RETRY_HUD_CONFIG=file;try{mergeStatusline(root,payload(cwd,{quota:{'gemini-5h':{remaining_fraction:0,reset_in_seconds:3600},'gemini-weekly':{remaining_fraction:.005,reset_in_seconds:90000}}}),1000);let n=0;const r=scheduleFromStop(root,{terminationReason:'error',error:'429 Individual quota reached',fullyIdle:true,conversationId:conv,workspacePaths:[cwd]},{now:1000,spawnWorker:()=>n++});assert.equal(r.scheduled,false);assert.equal(n,0);assert.equal(loadNative(root,conv).status,'WEEKLY_BLOCKED');}finally{old===undefined?delete process.env.AGY_RETRY_HUD_CONFIG:process.env.AGY_RETRY_HUD_CONFIG=old;}});
test('session retry off blocks Stop hook while session on overrides global off',()=>{const root=temp(),cwd=temp('agy-work-'),file=withConfig(root,c=>c.retry.enabled=true),old=process.env.AGY_RETRY_HUD_CONFIG;process.env.AGY_RETRY_HUD_CONFIG=file;try{mergeStatusline(root,payload(cwd),1000);setConversationOverride(root,'retry',conv,'off');let n=0;scheduleFromStop(root,{terminationReason:'error',error:'503 service unavailable',fullyIdle:true,conversationId:conv},{now:1000,spawnWorker:()=>n++});assert.equal(loadNative(root,conv).status,'RETRY_OFF');assert.equal(n,0);const c=JSON.parse(fs.readFileSync(file));c.retry.enabled=false;fs.writeFileSync(file,JSON.stringify(c));setConversationOverride(root,'retry',conv,'on');const r=scheduleFromStop(root,{terminationReason:'error',error:'503 service unavailable',fullyIdle:true,conversationId:conv},{now:2000,config:{transientBaseMs:1000,transientCapMs:1000,jitterMs:0},spawnWorker:()=>n++});assert.equal(r.scheduled,true);assert.equal(n,1);}finally{old===undefined?delete process.env.AGY_RETRY_HUD_CONFIG:process.env.AGY_RETRY_HUD_CONFIG=old;}});
test('automatic handoff snapshots at 85, defers unsafe state, and cancels rollover after native compaction',async()=>{const root=temp(),cwd=temp('agy-work-');fs.writeFileSync(path.join(cwd,'x.txt'),'x');const file=withConfig(root,c=>{c.handoff.semanticSummary=false;c.handoff.autoCreateNewSession=false;}),old=process.env.AGY_RETRY_HUD_CONFIG;process.env.AGY_RETRY_HUD_CONFIG=file;try{let spawned=0;mergeStatusline(root,payload(cwd,{context_window:{used_percentage:85,context_window_size:1_000_000}}),1000);let r=scheduleAutoHandoff(root,payload(cwd,{context_window:{used_percentage:85,context_window_size:1_000_000}}),{now:1000,spawnWorker:()=>spawned++});assert.equal(r.scheduled,true);assert.equal(spawned,1);await runHandoffWorker(root,conv,{now:()=>1100});let s=loadNative(root,conv);assert.equal(s.handoff.quality,'mechanical');assert.equal(s.handoff.status,'READY');mergeStatusline(root,payload(cwd,{context_window:{used_percentage:96,context_window_size:1_000_000},task_count:1}),1200);r=scheduleAutoHandoff(root,payload(cwd,{context_window:{used_percentage:96,context_window_size:1_000_000},task_count:1}),{now:1200,spawnWorker:()=>spawned++});assert.equal(r.scheduled,false);assert.equal(loadNative(root,conv).handoff.status,'PENDING');mergeStatusline(root,payload(cwd,{context_window:{used_percentage:70,context_window_size:1_000_000}}),1300);scheduleAutoHandoff(root,payload(cwd,{context_window:{used_percentage:70,context_window_size:1_000_000}}),{now:1300,spawnWorker:()=>spawned++});s=loadNative(root,conv);assert.equal(Boolean(s.handoff.rolloverArmed),false);}finally{old===undefined?delete process.env.AGY_RETRY_HUD_CONFIG:process.env.AGY_RETRY_HUD_CONFIG=old;}});
test('HUD v2 keeps 5h and week on one row with spaced reset icon and exposes policy state',()=>{const cwd='/tmp/project',p=payload(cwd),text=renderNativeStatusline(p,{retryOverride:'on',effectiveRetry:true,effectiveHandoff:true,handoff:{status:'READY'}},1000,{color:false,bar_width:10,show_handoff:true},{retryEnabled:true,retryOverride:'on',handoffEnabled:true});const lines=text.split('\n');assert.equal(lines.length,2);assert.match(lines[0],/handoff:READY/);assert.match(lines[0],/retry:SESSION/);assert.match(lines[1],/5h .*↻ \S+/);assert.match(lines[1],/week .*↻ \S+/);});
test('95% safe context can roll over to a fresh conversation without reusing the old conversation id',async()=>{const root=temp(),cwd=temp('agy-roll-'),file=withConfig(root,c=>{c.handoff.semanticSummary=false;c.handoff.autoCreateNewSession=true;}),old=process.env.AGY_RETRY_HUD_CONFIG;process.env.AGY_RETRY_HUD_CONFIG=file;try{const p=payload(cwd,{context_window:{used_percentage:96,context_window_size:1_000_000}});mergeStatusline(root,p,1000);scheduleAutoHandoff(root,p,{now:1000,spawnWorker:()=>{}});let calls=0,sent='';const newId='abcdef12-3456-7890-abcd-ef1234567890',adapter=cfg=>{calls++;assert.equal(cfg.conversation,null,'rollover must create a new conversation');return {async *events(){yield {event:'init',conversation_id:newId,init:{cwd}};yield {event:'result',result:{conversation_id:newId,status:'SUCCESS',response:'continued'}};},async send(m){sent=m;},async close(){return {clean:true};},async abort(){return {clean:false};}}};const out=await runHandoffWorker(root,conv,{now:()=>1100,adapter});assert.equal(calls,1);assert.equal(out.status,'SUCCEEDED');assert.equal(out.rolloverConversationId,newId);assert.match(sent,/handoff/i);assert.equal(out.handoff.newConversationId,newId);}finally{old===undefined?delete process.env.AGY_RETRY_HUD_CONFIG:process.env.AGY_RETRY_HUD_CONFIG=old;}});
test('90% safe context upgrades mechanical checkpoint to semantic handoff using the same conversation',async()=>{const root=temp(),cwd=temp('agy-sem-'),file=withConfig(root,c=>{c.handoff.semanticSummary=true;c.handoff.autoCreateNewSession=false;}),old=process.env.AGY_RETRY_HUD_CONFIG;process.env.AGY_RETRY_HUD_CONFIG=file;try{const p=payload(cwd,{context_window:{used_percentage:91,context_window_size:1_000_000}});mergeStatusline(root,p,1000);scheduleAutoHandoff(root,p,{now:1000,spawnWorker:()=>{}});let sent='',calls=0;const adapter=cfg=>{calls++;assert.equal(cfg.conversation,conv);return {async *events(){yield {event:'init',conversation_id:conv,init:{cwd}};yield {event:'result',result:{conversation_id:conv,status:'SUCCESS',response:'# Goal\n\nContinue portable work.\n\n# Next Step\n\nRun tests.\n'}};},async send(m){sent=m;},async close(){return {clean:true};},async abort(){return {clean:false};}}};const out=await runHandoffWorker(root,conv,{now:()=>1100,adapter});assert.equal(calls,1);assert.match(sent,/HANDOFF MUST BE EXECUTABLE/);assert.equal(out.handoff.quality,'semantic');assert.equal(out.handoff.status,'READY');}finally{old===undefined?delete process.env.AGY_RETRY_HUD_CONFIG:process.env.AGY_RETRY_HUD_CONFIG=old;}});

test('wide HUD never truncates quota label',()=>{const cwd=temp('agy-work-'),state=snapshotFromStatusline(payload(cwd),1000),text=renderNativeStatusline(payload(cwd),state,1000,{color:false,compact:false});assert.doesNotMatch(text,/\bquot\s/);assert.match(text,/\bquota\s+5h/);});


test('HUD wide grid aligns ctx and 5h bars plus percentage columns',()=>{
 const cwd='/tmp/project';
 const p=payload(cwd,{terminal_width:180,context_window:{used_percentage:4,context_window_size:1_000_000},quota:{'gemini-5h':{remaining_fraction:.99,reset_in_seconds:3600},'gemini-weekly':{remaining_fraction:.06,reset_in_seconds:90000}}});
 const text=renderNativeStatusline(p,{effectiveRetry:true,effectiveHandoff:false},1000,{color:false,compact:false,bar_width:10,show_tokens:false},{retryEnabled:true,retryOverride:'inherit',handoffEnabled:false});
 const lines=text.split('\n');assert.equal(lines.length,3);
 const ctxBar=lines[1].search(/[█░]{10}/),quotaBar=lines[2].search(/[█░]{10}/);assert.equal(ctxBar,quotaBar,'ctx and 5h bars must start in the same visual column');
 assert.equal(lines[1].indexOf('%'),lines[2].indexOf('%'),'ctx and 5h percentage signs must align');
 assert.match(lines[2],/quota\s+5h\s+[█░]{10}\s+99% left\s+↻ 1h00m\s+│\s+week\s+[█░]{10}\s+6% left\s+↻ 1d1h/);
});

test('HUD percentage colors follow approved semantic thresholds',()=>{
 assert.equal(metricColorCode('context',69),'92');
 assert.equal(metricColorCode('context',70),'93');
 assert.equal(metricColorCode('context',85),'38;5;208');
 assert.equal(metricColorCode('context',95),'91');
 assert.equal(metricColorCode('quota',70),'92');
 assert.equal(metricColorCode('quota',69),'93');
 assert.equal(metricColorCode('quota',29),'38;5;208');
 assert.equal(metricColorCode('quota',9),'91');
});


test('compact HUD defaults to two lines and keeps ctx plus 5h/week quotas in one metric row when wide',()=>{
 const cwd='/tmp/project',p=payload(cwd,{terminal_width:160,context_window:{used_percentage:4,context_window_size:1_000_000},quota:{'gemini-5h':{remaining_fraction:.99,reset_in_seconds:3600},'gemini-weekly':{remaining_fraction:.06,reset_in_seconds:90000}}});
 const text=renderNativeStatusline(p,{effectiveRetry:true,effectiveHandoff:false},1000,{color:false,bar_width:10},{retryEnabled:true,retryOverride:'inherit',handoffEnabled:false});
 const lines=text.split('\n');assert.equal(lines.length,2);assert.match(lines[0],/retry:ON/);assert.match(lines[0],/handoff:OFF/);assert.match(lines[1],/ctx .*4%/);assert.match(lines[1],/5h .*99% .*↻ 1h00m/);assert.match(lines[1],/week .*6% .*↻ 1d1h/);
});
