import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {mergeStatusline} from '../src/native.js';
function temp(p='agy-ctl-'){return fs.mkdtempSync(path.join(os.tmpdir(),p));}const conv='12345678-abcd-ef01-2345-6789abcdef01';
test('agy-retryctl controls current workspace session and creates/list handoffs deterministically',()=>{const base=temp(),root=path.join(base,'state'),cwd=path.join(base,'project'),config=path.join(base,'config.json');fs.mkdirSync(cwd,{recursive:true});mergeStatusline(root,{conversation_id:conv,cwd,workspace:{current_dir:cwd},model:{id:'gemini-test'},context_window:{used_percentage:20},quota:{},agent_state:'idle',pending_input_count:0,tool_confirmation_pending:false,terminal_width:100},Date.now());const cli=path.resolve('src/retryctl.js'),env={...process.env,AGY_RETRY_STATE_DIR:path.dirname(root),AGY_RETRY_HUD_CONFIG:config};let r=spawnSync(process.execPath,[cli,'retry','off','--config',config],{cwd,env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);r=spawnSync(process.execPath,[cli,'retry','session','on','--state-root',root,'--config',config,'--json'],{cwd,env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).effective,true);r=spawnSync(process.execPath,[cli,'handoff','create','--state-root',root,'--config',config,'--json'],{cwd,env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);const h=JSON.parse(r.stdout);assert.ok(h.handoffId);r=spawnSync(process.execPath,[cli,'handoff','list','--state-root',root,'--json'],{cwd,env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout)[0].id,h.handoffId);});

test('agy-retryctl exposes setup status and repair control plane',()=>{
 const home=temp('agy-ctl-home-'),pluginDir=path.join(home,'.gemini','config','plugins','agy-retry-hud'),env={...process.env,HOME:home,USERPROFILE:home,XDG_CONFIG_HOME:path.join(home,'.config'),XDG_STATE_HOME:path.join(home,'.state')};
 fs.mkdirSync(path.dirname(pluginDir),{recursive:true});fs.cpSync(path.resolve('plugin/agy-retry-hud'),pluginDir,{recursive:true});
 const cli=path.resolve('src/retryctl.js');let r=spawnSync(process.execPath,[cli,'setup','status','--json'],{env,encoding:'utf8'});assert.equal(r.status,4);let out=JSON.parse(r.stdout);assert.equal(out.installed,true);assert.equal(out.skills.setup,true);
 r=spawnSync(process.execPath,[cli,'setup','repair','--json'],{env,encoding:'utf8'});out=JSON.parse(r.stdout);assert.equal(out.doctor.statuslineWired,true);assert.equal(out.doctor.hooksReady,true);assert.equal(out.doctor.skillsReady,true);
});
