import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
test('plugin packages all v0.5 skills and portable schema',()=>{const root=path.resolve('plugin/agy-retry-hud'),skills=['retry','handoff','continue-handoff','handoff-status','retry-status','setup','hud-control','daemon-control','doctor'];for(const name of skills){const file=path.join(root,'skills',name,'SKILL.md');assert.equal(fs.existsSync(file),true,name);const text=fs.readFileSync(file,'utf8');assert.match(text,new RegExp(`name: ${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`));assert.match(text,/description:/);}const schema=JSON.parse(fs.readFileSync(path.join(root,'shared','handoff-schema-v1.json'),'utf8'));assert.equal(schema.properties.format.const,'agy-retry-handoff');assert.equal(schema.properties.version.const,1);});
test('handoff and retry skills expose deterministic global/session controls and portable continuation flow',()=>{const root=path.resolve('plugin/agy-retry-hud','skills'),retry=fs.readFileSync(path.join(root,'retry','SKILL.md'),'utf8'),handoff=fs.readFileSync(path.join(root,'handoff','SKILL.md'),'utf8'),cont=fs.readFileSync(path.join(root,'continue-handoff','SKILL.md'),'utf8');assert.match(retry,/retry session on\|off\|inherit/);assert.match(retry,/WEEKLY_BLOCKED/);assert.match(handoff,/handoff session on\|off\|inherit/);assert.match(handoff,/handoff create --json/);assert.match(cont,/handoff list --json/);assert.match(cont,/\.agyh/);assert.match(cont,/workspace-relative/);});

test('setup skill checks and repairs deterministic HUD components',()=>{const text=fs.readFileSync(path.resolve('plugin/agy-retry-hud/skills/setup/SKILL.md'),'utf8');assert.match(text,/agy-retryctl setup status --json/);assert.match(text,/agy-retryctl setup repair --json/);assert.match(text,/--force-statusline/);assert.match(text,/reinstallRequired/);});


test('all packaged skill frontmatter avoids invalid plain scalars with colon-space',()=>{const root=path.resolve('plugin/agy-retry-hud/skills');for(const name of fs.readdirSync(root)){const file=path.join(root,name,'SKILL.md');if(!fs.existsSync(file))continue;const lines=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n').split('\n'),end=lines.indexOf('---',1);assert.equal(lines[0],'---',name);assert.ok(end>1,name);const desc=lines.slice(1,end).find(x=>/^description:\s*/.test(x));assert.ok(desc,name);const value=desc.replace(/^description:\s*/,'').trim();if(value.includes(': '))assert.match(value,/^(?:".*"|'.*'|[>|])$/,name);}});

test('v0.5 control skills use deterministic local commands',()=>{const root=path.resolve('plugin/agy-retry-hud/skills'),hud=fs.readFileSync(path.join(root,'hud-control','SKILL.md'),'utf8'),daemon=fs.readFileSync(path.join(root,'daemon-control','SKILL.md'),'utf8'),doctor=fs.readFileSync(path.join(root,'doctor','SKILL.md'),'utf8');assert.match(hud,/agy-retryctl hud hide/);assert.match(hud,/agy-retryctl hud off/);assert.match(daemon,/daemon start|start.*stop/s);assert.match(doctor,/agy-retryctl doctor --json/);});
