import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash,randomBytes} from 'node:crypto';
import {atomicJSON} from './state.js';
import {createZip,readZip} from './zip.js';

export const HANDOFF_FORMAT='agy-retry-handoff';
export const HANDOFF_VERSION=1;
const SENSITIVE_BASENAME=[/^\.env(?:\.|$)/i,/\.pem$/i,/\.key$/i,/^credentials/i,/^secrets?/i];
const SENSITIVE_PATH=[/(^|\/)node_modules\//,/(^|\/)\.git\//,/(^|\/)\.venv\//,/(^|\/)venv\//,/(^|\/)dist\//,/(^|\/)build\//];
const SECRET_TEXT=[/-----BEGIN [A-Z ]*PRIVATE KEY-----/,/\bAWS_SECRET(?:_ACCESS_KEY)?\b\s*[:=]/i,/\b(?:PASSWORD|TOKEN|DATABASE_URL)\s*[:=]\s*\S+/i];

function sha256(data){return createHash('sha256').update(data).digest('hex');}
function nowId(now=Date.now()){const d=new Date(now),stamp=d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return `h-${stamp}-${randomBytes(3).toString('hex')}`;}
function run(cwd,args,{allowFail=false,max=2*1024*1024}={}){const r=spawnSync('git',args,{cwd,encoding:'utf8',windowsHide:true,maxBuffer:max,shell:false});if(r.error){if(allowFail)return '';throw r.error;}if(r.status!==0){if(allowFail)return '';throw Error(`git ${args.join(' ')} failed: ${(r.stderr||r.stdout||'').trim()}`);}return (r.stdout||'').trimEnd();}
function real(p){try{return fs.realpathSync(p);}catch{return path.resolve(p);}}
export function handoffRoot(cwd){return path.join(real(cwd),'.agy-retry','handoffs');}
export function normalizeRemote(remote=''){return String(remote).trim().replace(/^git@([^:]+):/,'ssh://git@$1/').replace(/\.git$/,'').replace(/\/$/,'').toLowerCase();}
export function workspaceIdentity(cwd){cwd=real(cwd);const top=run(cwd,['rev-parse','--show-toplevel'],{allowFail:true});if(!top)return {type:'directory',name:path.basename(cwd)};const root=real(top),remote=run(root,['config','--get','remote.origin.url'],{allowFail:true}),branch=run(root,['rev-parse','--abbrev-ref','HEAD'],{allowFail:true}),head=run(root,['rev-parse','HEAD'],{allowFail:true}),base=run(root,['merge-base','HEAD','HEAD~1'],{allowFail:true})||head;return {type:'git',remote:normalizeRemote(remote),branch,baseCommit:base,headCommit:head,name:path.basename(root)};}
export function workspaceStatus(cwd){cwd=real(cwd);const top=run(cwd,['rev-parse','--show-toplevel'],{allowFail:true});if(!top)return {git:false,status:'',changedFiles:[],untracked:[]};const root=real(top),status=run(root,['status','--porcelain=v1'],{allowFail:true}),lines=status?status.split(/\r?\n/):[],changed=[],untracked=[];for(const line of lines){const file=line.slice(3).replace(/^"|"$/g,'');if(line.startsWith('??'))untracked.push(file);else changed.push(file);}return {git:true,status,changedFiles:[...new Set(changed)],untracked:[...new Set(untracked)],diff:run(root,['diff','--binary'],{allowFail:true,max:8*1024*1024}),stagedDiff:run(root,['diff','--cached','--binary'],{allowFail:true,max:8*1024*1024})};}
export function ensureLocalExcluded(cwd){const gitDir=run(cwd,['rev-parse','--git-dir'],{allowFail:true});if(!gitDir)return false;const file=path.resolve(cwd,gitDir,'info','exclude');fs.mkdirSync(path.dirname(file),{recursive:true});let text='';try{text=fs.readFileSync(file,'utf8');}catch{}if(!text.split(/\r?\n/).includes('.agy-retry/'))fs.appendFileSync(file,(text&&!text.endsWith('\n')?'\n':'')+'.agy-retry/\n');return true;}
export function isSensitivePath(rel){rel=String(rel).replaceAll('\\','/');const base=path.posix.basename(rel);return SENSITIVE_BASENAME.some(r=>r.test(base))||SENSITIVE_PATH.some(r=>r.test(rel));}
export function scanSecretText(text){const hits=[];for(const r of SECRET_TEXT)if(r.test(String(text)))hits.push(r.source);return hits;}
function safeRel(rel){rel=String(rel).replaceAll('\\','/').replace(/^\.\//,'');if(!rel||rel.startsWith('/')||/^[A-Za-z]:\//.test(rel)||rel.split('/').some(x=>x==='..'))throw Error('unsafe relative path: '+rel);return rel;}
function yamlSafe(s){return String(s??'').replace(/[\r\n]+/g,' ').replace(/:/g,'-').slice(0,200);}
function validateManifest(manifest){
 if(!manifest||typeof manifest!=='object'||Array.isArray(manifest))throw Error('invalid handoff manifest');
 if(manifest.format!==HANDOFF_FORMAT||manifest.version!==HANDOFF_VERSION)throw Error('unsupported handoff format/version');
 for(const key of ['handoffId','project','createdAt','reason','quality','status'])if(typeof manifest[key]!=='string'||!manifest[key])throw Error('invalid handoff manifest field: '+key);
 if(!/^h-[A-Za-z0-9TZ-]+$/.test(manifest.handoffId))throw Error('invalid handoff manifest field: handoffId');
 if(!['mechanical','semantic'].includes(manifest.quality))throw Error('invalid handoff manifest field: quality');
 if(!manifest.workspaceIdentity||typeof manifest.workspaceIdentity!=='object'||Array.isArray(manifest.workspaceIdentity))throw Error('invalid handoff manifest field: workspaceIdentity');
 if(manifest.sourceConversationId!==null&&manifest.sourceConversationId!==undefined&&typeof manifest.sourceConversationId!=='string')throw Error('invalid handoff manifest field: sourceConversationId');
 if(Number.isNaN(Date.parse(manifest.createdAt)))throw Error('invalid handoff manifest field: createdAt');
 return manifest;
}
export const CONTINUE_PROMPT=`Continue the task described by the supplied portable handoff. Treat the handoff as a checkpoint, not as unquestionable truth. First validate the current workspace against the handoff manifest, then inspect the current repository state, relevant files, Git status, and referenced plans/specifications. Confirm which recorded completed actions are still reflected in the workspace. Do not repeat completed operations or side effects. Resolve any items marked uncertain before continuing. Machine-specific paths from the source environment must not be reused; resolve all repository paths relative to the current workspace root. Preserve the approved requirements, decisions, constraints, and scope documented in the handoff. Continue from the first unfinished actionable step. If the workspace does not match, required files are missing, or the recorded state cannot be verified, stop and ask for clarification rather than guessing.`;
export const HANDOFF_PROMPT=`Create a continuation handoff for another agent session that may run on a different machine and has no access to this conversation history. Capture the task goal, explicit user requirements, approved decisions, current implementation state, completed work, unfinished work, relevant workspace-relative files, test evidence, known failures, uncertain side effects, and the exact next action. Distinguish confirmed facts from assumptions. Do not copy the full conversation. Do not include credentials, tokens, secrets, machine-specific absolute paths, or irrelevant history. Do not claim an operation succeeded unless its result was verified. Identify operations that must not be repeated. References to repository files must be relative to the workspace root. The handoff must be sufficient for a new session to safely continue without relying on the original conversation ID. HANDOFF MUST BE EXECUTABLE, NOT NARRATIVE.`;
function mechanicalMarkdown({id,project,createdAt,reason,workspace,status,conversationId,checkpoint,tests=[]}){const changed=status.changedFiles.length?status.changedFiles.map(x=>`- \`${x}\``).join('\n'):'- None recorded';return `---\nhandoff_version: 1\nproject: ${yamlSafe(project)}\ncreated_at: ${new Date(createdAt).toISOString()}\nreason: ${yamlSafe(reason)}\nquality: mechanical\n---\n\n# Goal\n\nMechanical checkpoint. Semantic task summary was not available.\n\n# User Requirements\n\n- Recover from the project documents and current workspace before changing code.\n\n# Decisions Already Approved\n\n- Preserve confirmed work and do not repeat side effects.\n\n# Current Architecture / Approach\n\n- Workspace identity is recorded in \`workspace.json\`.\n\n# Completed Work\n\n- See current repository state and referenced project documents.\n\n# Work In Progress\n\n- Reconcile this checkpoint with the current workspace.\n\n# Last Confirmed Checkpoint\n\n${checkpoint?String(checkpoint):'No semantic checkpoint was supplied.'}\n\n# Files Changed\n\n${changed}\n\n# Tests / Verification\n\n${tests.length?tests.map(x=>`- ${x}`).join('\n'):'- No test evidence recorded by the mechanical snapshot.'}\n\n# Known Problems\n\n- Semantic context may be incomplete because this is a mechanical fallback.\n\n# Uncertain Side Effects\n\n- Verify any operation not represented in the repository state before repeating it.\n\n# Do Not Repeat\n\n- Do not repeat deployments, migrations, external writes, or destructive commands unless their prior outcome is verified.\n\n# Next Step\n\n1. Validate the workspace against \`manifest.json\` and \`workspace.json\`.\n2. Inspect Git status and relevant specs/plans.\n3. Recover the first unfinished actionable step.\n\n# Relevant Documents\n\n- Project-relative documents should be discovered from the current workspace.\n\n# Continuation Contract\n\n${CONTINUE_PROMPT}\n\n<!-- source conversation is provenance only: ${conversationId||'unknown'}; handoff ${id} -->\n`;}
function writeText(file,text){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,String(text),'utf8');}
function json(file,v){atomicJSON(file,v);}
export function handoffDir(cwd,id){if(!/^h-[A-Za-z0-9TZ-]+$/.test(id))throw Error('invalid handoff id');return path.join(handoffRoot(cwd),id);}
function includeSelectedUntracked({cwd,dir,status,includeUntracked=[]}){
 if(!Array.isArray(includeUntracked)||includeUntracked.length===0)return [];
 const allowed=new Set(status.untracked.map(x=>String(x).replaceAll('\\','/'))),included=[];
 for(const raw of includeUntracked){
  const rel=safeRel(raw);if(!allowed.has(rel))throw Error('requested untracked file is not currently untracked: '+rel);
  if(isSensitivePath(rel))throw Error('sensitive untracked path blocked from handoff: '+rel);
  const source=path.resolve(cwd,rel),root=path.resolve(cwd);if(source!==root&&!source.startsWith(root+path.sep))throw Error('untracked path escapes workspace: '+rel);
  const st=fs.statSync(source);if(!st.isFile())throw Error('only regular untracked files may be included: '+rel);if(st.size>5*1024*1024)throw Error('untracked file exceeds 5 MiB portable limit: '+rel);
  const data=fs.readFileSync(source);if(data.includes(0))throw Error('binary untracked files require external transfer and are not embedded: '+rel);
  const text=data.toString('utf8'),hits=scanSecretText(text);if(hits.length)throw Error('potential secret blocked in untracked file: '+rel);
  const target=path.join(dir,'git','untracked-files',...rel.split('/'));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,data,{mode:0o600});included.push(rel);
 }
 return included;
}
export function createHandoff({cwd=process.cwd(),conversationId='',reason='manual',quality='mechanical',semanticText='',checkpoint='',tests=[],now=Date.now(),portable=false,output,includeUntracked=[]}={}){
 cwd=real(cwd);ensureLocalExcluded(cwd);const id=nowId(now),dir=handoffDir(cwd,id),workspace=workspaceIdentity(cwd),status=workspaceStatus(cwd),project=workspace.name||path.basename(cwd),createdAt=now;
 const manifest={format:HANDOFF_FORMAT,version:HANDOFF_VERSION,handoffId:id,project,createdAt:new Date(now).toISOString(),reason,quality:semanticText?'semantic':quality,sourceConversationId:conversationId||null,workspaceIdentity:workspace,status:'READY'};
 const state={schemaVersion:1,handoffId:id,status:'READY',quality:manifest.quality,reason,sourceConversationId:conversationId||null,createdAt,consumedAt:null,consumedByConversationId:null};
 const workspaceDoc={...workspace,sourceMachinePath:cwd,pathBinding:'informational-only'};
 writeText(path.join(dir,'HANDOFF.md'),semanticText?.trim()||mechanicalMarkdown({id,project,createdAt,reason,workspace,status,conversationId,checkpoint,tests}));
 writeText(path.join(dir,'CONTINUE.md'),CONTINUE_PROMPT+'\n');json(path.join(dir,'manifest.json'),manifest);json(path.join(dir,'state.json'),state);json(path.join(dir,'workspace.json'),workspaceDoc);writeText(path.join(dir,'git','status.txt'),status.status+'\n');json(path.join(dir,'git','untracked.json'),status.untracked);if(status.diff)writeText(path.join(dir,'git','diff.patch'),status.diff+'\n');if(status.stagedDiff)writeText(path.join(dir,'git','staged.diff.patch'),status.stagedDiff+'\n');const included=includeSelectedUntracked({cwd,dir,status,includeUntracked});json(path.join(dir,'git','untracked-included.json'),included);json(path.join(dir,'evidence','tests.json'),tests);
 if(portable)return {...manifest,dir,includedUntracked:included,portableFile:exportHandoff({cwd,id,output})};return {...manifest,dir,includedUntracked:included};
}
export function finalizeSemanticHandoff({cwd=process.cwd(),id,text}){if(!String(text||'').trim())throw Error('semantic handoff text required');const hits=scanSecretText(text);if(hits.length)throw Error('semantic handoff appears to contain a secret');const dir=handoffDir(cwd,id),manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8')),state=JSON.parse(fs.readFileSync(path.join(dir,'state.json'),'utf8'));writeText(path.join(dir,'HANDOFF.md'),String(text).trim()+'\n');manifest.quality='semantic';state.quality='semantic';json(path.join(dir,'manifest.json'),manifest);json(path.join(dir,'state.json'),state);return {id,dir,quality:'semantic'};}
export function listHandoffs({cwd=process.cwd()}={}){const root=handoffRoot(cwd);let dirs=[];try{dirs=fs.readdirSync(root,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name);}catch(e){if(e.code==='ENOENT')return [];throw e;}return dirs.map(id=>{try{const d=handoffDir(cwd,id),m=JSON.parse(fs.readFileSync(path.join(d,'manifest.json'),'utf8')),s=JSON.parse(fs.readFileSync(path.join(d,'state.json'),'utf8'));return {id,project:m.project,createdAt:m.createdAt,status:s.status,quality:s.quality,reason:m.reason,dir:d};}catch{return null;}}).filter(Boolean).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));}
export function loadHandoff({cwd=process.cwd(),id}){const dir=handoffDir(cwd,id),manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8')),state=JSON.parse(fs.readFileSync(path.join(dir,'state.json'),'utf8'));validateManifest(manifest);if(manifest.handoffId!==id)throw Error('invalid handoff manifest id');return {dir,manifest,state,handoff:fs.readFileSync(path.join(dir,'HANDOFF.md'),'utf8'),continuePrompt:fs.readFileSync(path.join(dir,'CONTINUE.md'),'utf8'),workspace:JSON.parse(fs.readFileSync(path.join(dir,'workspace.json'),'utf8'))};}
export function validateWorkspace(expected,cwd=process.cwd()){const actual=workspaceIdentity(cwd);if(expected.type==='git'){if(actual.type!=='git')return {ok:false,reason:'current workspace is not a git repository',expected,actual};if(expected.remote&&actual.remote&&normalizeRemote(expected.remote)!==normalizeRemote(actual.remote))return {ok:false,reason:'git remote mismatch',expected,actual};if(expected.headCommit){const exists=run(cwd,['cat-file','-e',`${expected.headCommit}^{commit}`],{allowFail:true})!==''; // cat-file -e has no stdout, so use rev-parse instead below
 const r=spawnSync('git',['cat-file','-e',`${expected.headCommit}^{commit}`],{cwd,encoding:'utf8',windowsHide:true});if(r.status!==0)return {ok:false,reason:'recorded commit missing',expected,actual};}
 }
 return {ok:true,expected,actual};}
function collectFiles(dir,prefix='handoff'){const out=[];function walk(current,rel){for(const ent of fs.readdirSync(current,{withFileTypes:true})){const r=rel?rel+'/'+ent.name:ent.name,p=path.join(current,ent.name);if(ent.isDirectory())walk(p,r);else if(ent.isFile()){safeRel(r);const data=fs.readFileSync(p);if(isSensitivePath(r))throw Error('sensitive path blocked from handoff: '+r);if(/\.(?:md|json|txt|patch)$/i.test(r)){const hits=scanSecretText(data.toString('utf8'));if(hits.length)throw Error('potential secret blocked in '+r);}out.push({name:prefix+'/'+r,data});}}}walk(dir,'');return out;}
export function exportHandoff({cwd=process.cwd(),id,output}={}){const h=loadHandoff({cwd,id}),entries=collectFiles(h.dir),checksums={};for(const e of entries)checksums[e.name]=sha256(e.data);entries.push({name:'handoff/checksums.json',data:Buffer.from(JSON.stringify({algorithm:'sha256',files:checksums},null,2)+'\n')});const name=`${String(h.manifest.project||'task').replace(/[^A-Za-z0-9._-]+/g,'-')}-${id}.agyh`,file=path.resolve(output||path.join(cwd,name));fs.writeFileSync(file,createZip(entries));return file;}
export function inspectPortable(file){const entries=readZip(fs.readFileSync(file)),map=new Map(entries.map(e=>[e.name,e.data]));for(const required of ['handoff/manifest.json','handoff/HANDOFF.md','handoff/CONTINUE.md','handoff/workspace.json','handoff/state.json','handoff/checksums.json'])if(!map.has(required))throw Error('portable handoff missing '+required);const manifest=validateManifest(JSON.parse(map.get('handoff/manifest.json').toString('utf8')));const checks=JSON.parse(map.get('handoff/checksums.json').toString('utf8'));if(checks?.algorithm!=='sha256'||!checks.files||typeof checks.files!=='object'||Array.isArray(checks.files))throw Error('invalid handoff checksums manifest');for(const [name,hash] of Object.entries(checks.files||{})){const data=map.get(name);if(!data||sha256(data)!==hash)throw Error('handoff checksum mismatch: '+name);}for(const e of entries){safeRel(e.name);if(isSensitivePath(e.name))throw Error('sensitive path in portable handoff: '+e.name);if(/\.(?:md|json|txt|patch)$/i.test(e.name)&&scanSecretText(e.data.toString('utf8')).length)throw Error('potential secret in portable handoff: '+e.name);}return {entries,map,manifest,workspace:JSON.parse(map.get('handoff/workspace.json').toString('utf8'))};}
export function importHandoff({cwd=process.cwd(),file}={}){cwd=real(cwd);const p=inspectPortable(file),id=p.manifest.handoffId;if(!/^h-[A-Za-z0-9TZ-]+$/.test(id))throw Error('invalid imported handoff id');ensureLocalExcluded(cwd);let dest=handoffDir(cwd,id);if(fs.existsSync(dest)){const existing=JSON.parse(fs.readFileSync(path.join(dest,'manifest.json'),'utf8'));if(JSON.stringify(existing)!==JSON.stringify(p.manifest))dest=handoffDir(cwd,id+'-imported');}
 fs.mkdirSync(dest,{recursive:true});const base='handoff/';for(const e of p.entries){if(e.name==='handoff/checksums.json'||!e.name.startsWith(base))continue;const rel=safeRel(e.name.slice(base.length)),target=path.resolve(dest,rel);if(target!==path.resolve(dest)&&!target.startsWith(path.resolve(dest)+path.sep))throw Error('portable handoff path traversal');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,e.data,{mode:0o600});}
 const st=JSON.parse(fs.readFileSync(path.join(dest,'state.json'),'utf8'));st.status='IMPORTED';json(path.join(dest,'state.json'),st);return {id:path.basename(dest),dir:dest,manifest:p.manifest,workspace:p.workspace,workspaceValidation:validateWorkspace(p.workspace,cwd)};}
export function markConsumed({cwd=process.cwd(),id,conversationId}){const h=loadHandoff({cwd,id});h.state.status='ACTIVE';h.state.consumedAt=new Date().toISOString();h.state.consumedByConversationId=conversationId||null;json(path.join(h.dir,'state.json'),h.state);return h.state;}
export function handoffSummary({cwd=process.cwd(),id}){const h=loadHandoff({cwd,id});return {id,manifest:h.manifest,state:h.state,workspaceValidation:validateWorkspace(h.workspace,cwd),dir:h.dir};}
